---
site_name: K8s Journey notes
site_url: https://puneetk.github.io/k8sjourney
site_description: Notes/Howtos/Links collected while working on K8s
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/puneetk/k8sjourney
edit_uri: ""

theme:
  name: material
  language: 'en'
  # logo:
  palette:
    scheme: slate

plugins:
  - search
  - macros

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
